### ISSUE TITLE
Add-on Exam Notifier bug

### ISSUE THREAD

**Issue by hhlp** [AnKing-Memberships/exam-notifier#13]
#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

Add-on Exam Notifier bug under flatpak simple crash ....

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ x] I've restarted Anki to see if it helps
 - [ x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x ] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x ] I've tried to disable other add-ons to see if there are any interactions present
 - [ x] My issue disappears when I hold shift while starting Anki.
 - [x ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 
I've disable all the add-ons and start anki with just Exam Notifier enabled same behaviour.

#### Information about your Anki set-up

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```
System : Linux
Distro : Fedora
Architecture : x86_64
Instalation Options : flatpak
Version :

flatpak list

Anki    net.ankiweb.Anki        2.1.58  stable  flathub-1       system
```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

flatpak version

```python

```
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.58 (ab8b1465) Python 3.9.15 Qt 6.4.2 PyQt 6.4.0
Platform: Linux-6.1.12-200.fc37.x86_64-x86_64-with-glibc2.35
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-02-22 17:56:20
Add-ons possibly involved: ⁨Exam Notifier⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 46, in cmd
  File "aqt.webview", line 153, in _onCmd
  File "aqt.webview", line 656, in _onBridgeCmd
  File "_aqt.hooks", line 5182, in __call__
  File "/home/hhlp/.var/app/net.ankiweb.Anki/data/Anki2/addons21/exam_notifier/deck_options.py", line 150, in on_webview_did_receive_js_message
    DeckConf(self._main_window, deck_legacy)
  File "aqt.deckconf", line 40, in __init__
  File "_aqt.hooks", line 1829, in __call__
  File "/home/hhlp/.var/app/net.ankiweb.Anki/data/Anki2/addons21/exam_notifier/deck_options_legacy.py", line 109, in on_deck_config_gui_loaded
    deck_config_tab = self._factory(parent=deck_conf_dialog)
  File "/home/hhlp/.var/app/net.ankiweb.Anki/data/Anki2/addons21/exam_notifier/deck_options_legacy.py", line 63, in __init__
    self._qdatetime_from_epoch(unix_time_now)
  File "/home/hhlp/.var/app/net.ankiweb.Anki/data/Anki2/addons21/exam_notifier/deck_options_legacy.py", line 89, in _qdatetime_from_epoch
    qdatetime.setTime_t(unix_epoch)
AttributeError: 'QDateTime' object has no attribute 'setTime_t'
```

same happened with the Oficial version, download from here: 2.1.60

https://github.com/ankitects/anki/releases

```python
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.60 (76d88073) Python 3.9.15 Qt 6.4.2 PyQt 6.4.0
Platform: Linux-6.1.12-200.fc37.x86_64-x86_64-with-glibc2.36
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-02-23 11:00:43
Add-ons possibly involved: ⁨Exam Notifier⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 46, in cmd
  File "aqt.webview", line 153, in _onCmd
  File "aqt.webview", line 656, in _onBridgeCmd
  File "_aqt.hooks", line 5182, in __call__
  File "/home/hhlp/.local/share/Anki2/addons21/exam_notifier/deck_options.py", line 150, in on_webview_did_receive_js_message
    DeckConf(self._main_window, deck_legacy)
  File "aqt.deckconf", line 40, in __init__
  File "_aqt.hooks", line 1829, in __call__
  File "/home/hhlp/.local/share/Anki2/addons21/exam_notifier/deck_options_legacy.py", line 109, in on_deck_config_gui_loaded
    deck_config_tab = self._factory(parent=deck_conf_dialog)
  File "/home/hhlp/.local/share/Anki2/addons21/exam_notifier/deck_options_legacy.py", line 63, in __init__
    self._qdatetime_from_epoch(unix_time_now)
  File "/home/hhlp/.local/share/Anki2/addons21/exam_notifier/deck_options_legacy.py", line 89, in _qdatetime_from_epoch
    qdatetime.setTime_t(unix_epoch)
AttributeError: 'QDateTime' object has no attribute 'setTime_t'
```

Regards.,

**Comment by hhlp** [comment]
i've download the latest one all works very well

from here: https://github.com/AnKing-Memberships/exam-notifier/releases/tag/1.4

Regards.,
