### ISSUE TITLE
Error when opening "Click here" on Deck Options

### ISSUE THREAD

**Issue by ncrees** [AnKing-Memberships/exam-notifier#14]
#### Problem description

I am trying to use the Exam Notifier add-on on the AnKing deck. When going to the options for the deck, and clicking "Click here!" will give me an error message that I will list below. 

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x ] I've restarted Anki to see if it helps
 - [x ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x ] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x ] I've tried to disable other add-ons to see if there are any interactions present
 - [x ] My issue disappears when I hold shift while starting Anki.
 - [x ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```
    
    Anki 2.1.56 (07fd88dd) Python 3.9.15 Qt 6.4.0 PyQt 6.4.0
    Platform: Windows-10-10.0.19044
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2023-03-25 13:08:46
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    AMBOSS Official  Medical School Step  Shelf Study Resource ['1044112126', 2022-03-07T06:06, 'None', '']
    Add Hyperlink ['318752047', 2022-05-23T09:16, 'None', '']
    Additional Card Fields Fork for 21 ['744725736', 2022-10-23T06:10, 'None', mod]
    Advanced Browser ['874215009', 2022-09-26T20:28, 'None', mod]
    Advanced Card Styles ['1625103157', 2021-12-28T12:49, 'None', '']
    AnKing Note Types Easy Customization ['952691989', 2023-03-21T06:45, 'None', mod]
    Anki Palace Butler ['butler', 2022-08-17T21:23, 'None', mod]
    Anki Simulator ['817108664', 2021-08-07T15:24, 'None', '']
    AnkiConnect ['2055492159', 2022-09-18T20:11, 'None', '']
    AnkiHub ['1322529746', 2023-03-23T20:23, 'None', '']
    Audiovisual Feedback ['231569866', 2022-06-29T08:28, '0.8', mod]
    Batch Editing ['291119185', 2019-09-19T13:04, 'None', '']
    Bionic Reading ['649714433', 2022-08-26T22:29, 'None', mod]
    Calculate New Cards To Do ['2014569756', 2022-05-19T01:38, 'None', mod]
    Clickable Tags v20 ['1739176371', 2022-01-30T17:58, 'None', '']
    Closet For Anki ['272311064', 2022-08-12T04:27, 'None', '']
    Colorful Tags  Hierarchical Tags ['594329229', 2022-09-15T11:06, 'None', '']
    Custom Background Image and Gear Icon ['1210908941', 2023-03-04T13:54, 'None', mod]
    Customize Keyboard Shortcuts ['24411424', 2022-09-14T05:12, 'None', mod]
    Edit Field During Review Cloze ['385888438', 2022-06-27T05:48, '6.13', mod]
    Exam Notifier ['exam_notifier', 2021-09-02T08:35, 'None', '']
    Export Single Tag For Sharing ['960563361', 2022-04-10T17:30, 'None', '']
    Extended Tag AddEdit Dialog ['1135507717', 2022-03-13T06:41, 'None', mod]
    Fastbar another toolbar for Anki 21 beta ['1955978390', 2019-11-23T11:54, 'None', '']
    Fastbar- with nightmode support ['46611790', 2023-02-17T18:18, 'None', '']
    Google Translate ['1536291224', 2022-11-12T19:00, 'None', '']
    High Yield Tags ['1918380616', 2023-01-10T14:14, 'None', mod]
    Hint Hotkeys ['1844908621', 2019-02-26T13:58, 'None', '']
    Image Editor ['307397307', 2022-09-08T00:09, 'None', mod]
    Image Occlusion Enhanced ['1374772155', 2022-04-09T03:15, 'None', '']
    Learning Step and Review Interval Retention ['1949865265', 2022-08-28T16:21, 'None', '']
    More Decks Stats and Time Left ['1556734708', 2022-10-09T08:05, 'None', mod]
    More Overview Stats 21 ['738807903', 2021-07-30T15:13, 'None', mod]
    New Cards Counter ['635082046', 2022-04-20T16:37, 'None', '']
    PDF Exporter ['1442112168', 2022-11-16T15:23, 'None', '']
    Placeholder- SCwCD ['390813456', 2022-11-26T10:55, 'None', '']
    Pokemanki ['633922407', 2021-02-24T13:49, 'None', '']
    Quick Colour Changing ['2491935955', 2022-07-24T00:29, 'None', mod]
    ReColor ['688199788', 2022-12-31T14:29, '2.4', mod]
    Remote Decks ['924929499', 2022-11-15T08:37, 'None', '']
    Reset Ease ['947935257', 2020-12-27T09:59, 'None', '']
    Review Heatmap ['1771074083', 2022-06-29T21:43, 'None', '']
    Special Fields ['1102281552', 2022-11-21T20:49, 'None', mod]
    Speed Focus Mode auto-alert auto-reveal auto-answer ['1046608507', 2022-12-16T06:24, 'None', mod]
    Straight Reward ['957961234', 2022-12-12T08:49, 'None', '']
    Symbols As You Type ['2040501954', 2022-06-08T00:09, 'None', '']
    Symbols ['1461102936', 2019-04-23T09:37, 'None', mod]
    The KING of Button Add-ons ['374005964', 2023-02-17T18:21, 'None', '']
    The KING of Study Timers ['907028815', 2022-04-20T14:14, 'None', mod]
    True Retention ['613684242', 2017-11-19T15:43, 'None', '']
    Web Browser - Search terms Import texts and images automatically ['864545277', 2022-08-02T16:49, 'None', mod]
    Weekends and Holidays ['1222550498', 2022-04-15T06:44, 'None', mod]
    Weekends and Holidays ['1992008104', 2022-12-19T20:24, 'None', '']
    Wrapper meta-addon ['396502676', 2022-06-18T14:31, 'None', '']
    Ze Add Note Id ['886709118', 2021-03-02T15:06, 'None', '']
    add-on dialog searchfilter bar ['561945101', 2021-12-05T15:28, 'None', '']
    put ALL due learning cards first modified v2 support ['1807121582', 2019-11-24T14:20, 'None', '']
    rebuild allempty some or all filtered decks ['104518886', 2023-03-19T13:20, 'None', '']
    uworld_qid_to_anki_search ['607963104', 2023-03-04T13:35, 'None', mod]
    
    ===IDs of active AnkiWeb add-ons===
    1044112126 104518886 1046608507 1102281552 1135507717 1210908941 1222550498 1322529746 1374772155 1442112168 1461102936 1536291224 1556734708 1625103157 1739176371 1771074083 1807121582 1844908621 1918380616 1949865265 1955978390 1992008104 2014569756 2040501954 2055492159 231569866 24411424 2491935955 272311064 291119185 307397307 318752047 374005964 385888438 390813456 396502676 46611790 561945101 594329229 607963104 613684242 633922407 635082046 649714433 688199788 738807903 744725736 817108664 864545277 874215009 886709118 907028815 924929499 947935257 952691989 957961234 960563361
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Contanki - Controller Support for Anki beta ['1898790263', 2023-02-01T20:04, 'v0.9.2-beta', '']

```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python
Debug info: 

Anki 2.1.56 (07fd88dd) Python 3.9.15 Qt 6.4.0 PyQt 6.4.0
 Platform: Windows-10-10.0.19044 
Flags: frz=True ao=True sv=2 
Add-ons, last update check: 2023-03-25 13:08:46  

Caught exception: 
Traceback (most recent call last): 
  File "aqt.webview", line 43, in cmd
   File "aqt.webview", line 150, in _onCmd
   File "aqt.webview", line 614, in _onBridgeCmd
   File "_aqt.hooks", line 4887, in __call__ 
  File "C:
\Users\ncrees\AppData\Roaming\Anki2\addons21\exam_notifier\deck_options.py", line 150, in on_webview_did_receive_js_message
     DeckConf(self._main_window, deck_legacy)
   File "aqt.deckconf", line 40, in __init__
   File "_aqt.hooks", line 1693, in __call__
   File "C:
\Users\ncrees\AppData\Roaming\Anki2\addons21\exam_notifier\deck_options_legacy.py", line 109, in on_deck_config_gui_loaded
     deck_config_tab = self._factory(parent=deck_conf_dialog)
   File "C:
\Users\ncrees\AppData\Roaming\Anki2\addons21\exam_notifier\deck_options_legacy.py", line 63, in __init__
     self._qdatetime_from_epoch(unix_time_now)
   File "C:
\Users\ncrees\AppData\Roaming\Anki2\addons21\exam_notifier\deck_options_legacy.py", line 89, in _qdatetime_from_epoch 
    qdatetime.setTime_t(unix_epoch)
 AttributeError: 'QDateTime' object has no attribute 'setTime_t' 
```

**Comment by ncrees** [comment]
Update:

I have deleted the 'Fastbar another toolbar for Anki 21 beta' add-on as it caused an error pop-up for when I just wanted to use the browser. However, the 'Exam Notifier' add-on still gives me the same error message as above.

**Comment by ncrees** [comment]
Downloaded latest file on github rather than on AnkiWeb and downloaded latest Anki version 2.1.60. Issue is resolved.
